# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.6.0" "africastalking>=1.2.9"

# Copy application code
COPY . .

# Expose no ports; uses stdio
# Default command
CMD ["python", "main.py"]
