[project]
name = "africas-talking-airtime-mcp-server"
version = "0.1.0"
description = "An MCP server that provides tools for interacting with Africa's Talking airtime service."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "africastalking>=1.2.9",
    "mcp[cli]>=1.6.0",
]
